export const bookSummaries = {
  Genesis: "God creates the world and chooses Abraham's family to bring blessing to all nations.",
  Exodus: "God saves Israel from slavery in Egypt and enters into a special relationship with them.",
  Leviticus: "God gives Israel instructions for how to worship Him.",
  Numbers: "Israel fails to trust and obey God, and wanders in the wilderness for 40 years.",
  Deuteronomy: "Moses gives Israel instructions for how to love and obey God in the Promised Land.",
  Joshua: "Joshua leads Israel to conquer the Promised Land and divides it among the twelve tribes.",
  Judges: "Israel cycles through turning from God, falling captive, calling to God, and being rescued by judges.",
  Ruth: "Two widows lose everything and find hope in Israel, leading to the birth of King David.",
  "1 Samuel": "Israel demands a king, who turns out to be quite a disappointment.",
  "2 Samuel": "David, a man after God's own heart, becomes king of Israel.",
  "1 Kings": "The kingdom has peace under Solomon, but afterward splits and both kingdoms turn from God.",
  "2 Kings": "Both kingdoms ignore God and his prophets until they fall captive to other empires.",
  "1 Chronicles":
    "A brief history of Israel from Adam to David, culminating with David commissioning the temple.",
  "2 Chronicles": "Solomon builds the temple, but after centuries of rejecting God, the Babylonians destroy it.",
  Ezra: "The Israelites rebuild the temple in Jerusalem and Ezra teaches them to obey God's laws.",
  Nehemiah: "Nehemiah rebuilds the wall around Jerusalem when the city is in bad shape.",
  Esther: "Esther must face the emperor to stop a genocidal plot against Israel.",
  Job: "Satan attacks a righteous man named Job, and Job and his friends debate why terrible things happen to him.",
  Psalms: "A collection of 150 songs that Israel sang to God and to each other.",
  Proverbs: "A collection of sayings written to help people make wise decisions that bring justice.",
  Ecclesiastes: "A philosophical exploration of the meaning of life with a surprisingly nihilistic tone.",
  "Song of Solomon": "A love song celebrating love, desire, and marriage.",
  Isaiah:
    "Isaiah warns Israel of future judgment but also tells of a coming king who will bear the sins of many.",
  Jeremiah: "God sends a prophet to warn Israel about coming Babylonian captivity, but the people don't listen.",
  Lamentations: "A collection of dirges lamenting the fall of Jerusalem after the Babylonian attacks.",
  Ezekiel: "God chooses Ezekiel to speak for Him to Israel, teaching them justice and the error of their ways.",
  Daniel:
    "Daniel becomes a high-ranking wise man in Babylonian and Persian empires with prophetic visions of Israel's future.",
  Hosea:
    "Hosea marries a prostitute who leaves him and he must bring her back—a picture of God's relationship with Israel.",
  Joel: "God sends a plague of locusts to judge Israel, but judgment on surrounding nations is also coming.",
  Amos: "A shepherd named Amos preaches against the injustice of the Northern Kingdom of Israel.",
  Obadiah: "Obadiah warns the neighboring nation of Edom that they will be judged for plundering Jerusalem.",
  Jonah: "A disobedient prophet runs from God, is swallowed by a great fish, then preaches to Nineveh.",
  Micah:
    "Micah confronts the leaders of Israel and Judah regarding their injustice and prophesies of perfect justice to come.",
  Nahum: "Nahum foretells of God's judgment on Nineveh, the capital of Assyria.",
  Habakkuk:
    "Habakkuk pleads with God to stop injustice in Judah but is surprised God will use violent Babylonians to do so.",
  Zephaniah:
    "God warns He will judge Israel and surrounding nations, but also restore them in peace and justice.",
  Haggai: "The people have abandoned restoring God's temple in Jerusalem, and Haggai takes them to task.",
  Zechariah:
    "Zechariah calls Israel to return to God and records prophetic visions showing what's happening behind the scenes.",
  Malachi:
    "God has been faithful to Israel, but they live disconnected from Him—so God sends Malachi to call them out.",
  Matthew:
    "This is an account of Jesus' life, death, and resurrection, focusing on Jesus as the true king of the Jews.",
  Mark: "This brief account of Jesus' earthly ministry highlights Jesus' authority and servanthood.",
  Luke: "Luke writes the most thorough account of Jesus' life, pulling together eyewitness testimonies.",
  John: "John lists stories of signs and miracles with the hope that readers will believe in Jesus.",
  Acts: "Jesus returns to the Father, the Holy Spirit comes to the church, and the gospel spreads throughout the world.",
  Romans: "Paul summarizes how the gospel of Jesus works in a letter to the churches at Rome.",
  "1 Corinthians":
    "Paul writes a disciplinary letter to a fractured church in Corinth and answers questions about Christian behavior.",
  "2 Corinthians": "Paul writes a letter of reconciliation to the church at Corinth and clears up some concerns.",
  Galatians:
    "Paul writes a heated letter correcting false teachers who say salvation comes from the law of Moses.",
  Ephesians: "Paul writes to the church at Ephesus about how to walk in grace, peace, and love.",
  Philippians: "An encouraging letter from Paul telling the church of Philippi how to have joy in Christ.",
  Colossians: "Paul writes the church at Colossae about who they are in Christ and how to walk in Christ.",
  "1 Thessalonians": "Paul encourages the church at Thessalonica to excel still more in faith, hope, and love.",
  "2 Thessalonians": "Paul instructs the Thessalonians on how to stand firm until the coming of Jesus.",
  "1 Timothy": "Paul gives Timothy instruction on how to lead a church with sound teaching and a godly example.",
  "2 Timothy": "Paul nears the end of his life and encourages Timothy to continue preaching the word.",
  Titus: "Paul advises Titus on how to lead orderly, counter-cultural churches on the island of Crete.",
  Philemon: "Paul strongly recommends that Philemon accept his runaway slave as a brother, not a slave.",
  Hebrews: "A letter encouraging Christians to cling to Christ despite persecution, because He is greater.",
  James: "A letter telling Christians to live in ways that demonstrate their faith in action.",
  "1 Peter": "Peter writes to Christians who are being persecuted, encouraging them to testify to the truth.",
  "2 Peter": "Peter reminds Christians about the truth of Jesus and warns that false teachers will come.",
  "1 John":
    "John writes about keeping Jesus' commands, loving one another, and important things Christians should know.",
  "2 John": "A very brief letter about walking in truth, love, and obedience.",
  "3 John": "An even shorter letter about Christian fellowship.",
  Jude: "A letter encouraging Christians to contend for the faith, even though ungodly persons have crept in unnoticed.",
  Revelation: "John sees visions of things that have been, things that are, and things that are yet to come.",
};

export const chapterCounts = {
  Genesis: 50,
  Exodus: 40,
  Leviticus: 27,
  Numbers: 36,
  Deuteronomy: 34,
  Joshua: 24,
  Judges: 21,
  Ruth: 4,
  "1 Samuel": 31,
  "2 Samuel": 24,
  "1 Kings": 22,
  "2 Kings": 25,
  "1 Chronicles": 29,
  "2 Chronicles": 36,
  Ezra: 10,
  Nehemiah: 13,
  Esther: 10,
  Job: 42,
  Psalms: 150,
  Proverbs: 31,
  Ecclesiastes: 12,
  "Song of Solomon": 8,
  Isaiah: 66,
  Jeremiah: 52,
  Lamentations: 5,
  Ezekiel: 48,
  Daniel: 12,
  Hosea: 14,
  Joel: 3,
  Amos: 9,
  Obadiah: 1,
  Jonah: 4,
  Micah: 7,
  Nahum: 3,
  Habakkuk: 3,
  Zephaniah: 3,
  Haggai: 2,
  Zechariah: 14,
  Malachi: 4,
  Matthew: 28,
  Mark: 16,
  Luke: 24,
  John: 21,
  Acts: 28,
  Romans: 16,
  "1 Corinthians": 16,
  "2 Corinthians": 13,
  Galatians: 6,
  Ephesians: 6,
  Philippians: 4,
  Colossians: 4,
  "1 Thessalonians": 5,
  "2 Thessalonians": 3,
  "1 Timothy": 6,
  "2 Timothy": 4,
  Titus: 3,
  Philemon: 1,
  Hebrews: 13,
  James: 5,
  "1 Peter": 5,
  "2 Peter": 3,
  "1 John": 5,
  "2 John": 1,
  "3 John": 1,
  Jude: 1,
  Revelation: 22,
};

export const bookAbbreviations = {
  Genesis: "GEN",
  Exodus: "EXO",
  Leviticus: "LEV",
  Numbers: "NUM",
  Deuteronomy: "DEU",
  Joshua: "JOS",
  Judges: "JDG",
  Ruth: "RUT",
  "1 Samuel": "1SA",
  "2 Samuel": "2SA",
  "1 Kings": "1KI",
  "2 Kings": "2KI",
  "1 Chronicles": "1CH",
  "2 Chronicles": "2CH",
  Ezra: "EZR",
  Nehemiah: "NEH",
  Esther: "EST",
  Job: "JOB",
  Psalms: "PSA",
  Proverbs: "PRO",
  Ecclesiastes: "ECC",
  "Song of Solomon": "SNG",
  Isaiah: "ISA",
  Jeremiah: "JER",
  Lamentations: "LAM",
  Ezekiel: "EZK",
  Daniel: "DAN",
  Hosea: "HOS",
  Joel: "JOL",
  Amos: "AMO",
  Obadiah: "OBA",
  Jonah: "JON",
  Micah: "MIC",
  Nahum: "NAM",
  Habakkuk: "HAB",
  Zephaniah: "ZEP",
  Haggai: "HAG",
  Zechariah: "ZEC",
  Malachi: "MAL",
  Matthew: "MAT",
  Mark: "MRK",
  Luke: "LUK",
  John: "JHN",
  Acts: "ACT",
  Romans: "ROM",
  "1 Corinthians": "1CO",
  "2 Corinthians": "2CO",
  Galatians: "GAL",
  Ephesians: "EPH",
  Philippians: "PHP",
  Colossians: "COL",
  "1 Thessalonians": "1TH",
  "2 Thessalonians": "2TH",
  "1 Timothy": "1TI",
  "2 Timothy": "2TI",
  Titus: "TIT",
  Philemon: "PHM",
  Hebrews: "HEB",
  James: "JAS",
  "1 Peter": "1PE",
  "2 Peter": "2PE",
  "1 John": "1JN",
  "2 John": "2JN",
  "3 John": "3JN",
  Jude: "JUD",
  Revelation: "REV",
};

export const categories = [
  {
    name: "Law",
    testament: "Old Testament",
    books: ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"],
    color: "linear-gradient(135deg, #2a2d35 0%, #1a1d25 100%)",
  },
  {
    name: "History",
    testament: "Old Testament",
    books: [
      "Joshua",
      "Judges",
      "Ruth",
      "1 Samuel",
      "2 Samuel",
      "1 Kings",
      "2 Kings",
      "1 Chronicles",
      "2 Chronicles",
      "Ezra",
      "Nehemiah",
      "Esther",
    ],
    color: "linear-gradient(135deg, #352d2a 0%, #251d1a 100%)",
  },
  {
    name: "Poetry",
    testament: "Old Testament",
    books: ["Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon"],
    color: "linear-gradient(135deg, #2d2a35 0%, #1d1a25 100%)",
  },
  {
    name: "Major Prophets",
    testament: "Old Testament",
    books: ["Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel"],
    color: "linear-gradient(135deg, #2a3530 0%, #1a251f 100%)",
  },
  {
    name: "Minor Prophets",
    testament: "Old Testament",
    books: [
      "Hosea",
      "Joel",
      "Amos",
      "Obadiah",
      "Jonah",
      "Micah",
      "Nahum",
      "Habakkuk",
      "Zephaniah",
      "Haggai",
      "Zechariah",
      "Malachi",
    ],
    color: "linear-gradient(135deg, #30352a 0%, #20251a 100%)",
  },
  {
    name: "Gospels",
    testament: "New Testament",
    books: ["Matthew", "Mark", "Luke", "John"],
    color: "linear-gradient(135deg, #2a3035 0%, #1a2025 100%)",
  },
  {
    name: "History",
    testament: "New Testament",
    books: ["Acts"],
    color: "linear-gradient(135deg, #352a30 0%, #251a20 100%)",
  },
  {
    name: "Paul's Letters",
    testament: "New Testament",
    books: [
      "Romans",
      "1 Corinthians",
      "2 Corinthians",
      "Galatians",
      "Ephesians",
      "Philippians",
      "Colossians",
      "1 Thessalonians",
      "2 Thessalonians",
      "1 Timothy",
      "2 Timothy",
      "Titus",
      "Philemon",
    ],
    color: "linear-gradient(135deg, #35302a 0%, #25201a 100%)",
  },
  {
    name: "General Epistles",
    testament: "New Testament",
    books: ["Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude"],
    color: "linear-gradient(135deg, #2a2a35 0%, #1a1a25 100%)",
  },
  {
    name: "Prophecy",
    testament: "New Testament",
    books: ["Revelation"],
    color: "linear-gradient(135deg, #332a35 0%, #231a25 100%)",
  },
];
